Game testing
MarvellousUbani/Tic-Tac-Toe pull request #6
Opened 2019-09-13 18:07 UTC by MarvellousUbani

2019-09-14 00:38 UTC, Ispirett requested changes
Hey, @KerronKing @MarvellousUbani Great!!! work with Testing 

![image](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png). 

However there are some testing missing.

- [x]  You should write a test for the player class, so you can make `player_spec` file.
- [x] There no test case for a game draw

[Optional] Not required 
You can add --format documentation to your `.rspec `. This gives a better display message from tests.

2019-09-17 00:03 UTC, bolah2009 commented
## Currently under review

2019-09-17 06:59 UTC, samgaco approved these changes
Hi @KerronKing and @MarvellousUbani :high_brightness: 

All the requirements have been covered, hence the project is approved, you can merge and submit the project completion form. Good luck with rails :100: 

----------------------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2019-09-17 06:59 UTC, samgaco commented on spec/board_spec.rb
> +      expect(board.check_win('X')).not_to eq(true)
Testing symbol2 might be a good idea as well

2019-09-17 10:11 UTC, merged